---
apiVersion: v1
kind: Pod
metadata:
  name: app1
spec:
  containers:
    - name: app1
      image: docker.io/xethub/counter-app:latest
      volumeMounts:
        - name: xet-flickr-30
          mountPath: /data
  volumes:
    - name: xet-flickr-30
      csi:
        driver: csi.xethub.xetdata.com
        readOnly: true
        volumeAttributes:
          repo: https://xethub.com/XetHub/Flickr30k.git
          commit: main
    # following is setup for a private repo mount
    # requires a secret configured like in secret.yaml.template
    #- name: private-repo
      #csi:
        #driver: csi.xethub.xetdata.com
        #readOnly: true
        #volumeAttributes:
          #repo: <https url of private repo>
          #commit: main
        #nodePublishSecretRef:
          #name: <secret name>
