apiVersion: v1
kind: ServiceAccount
metadata:
  name: xet-csi-node-sa
  labels:
    app.kubernetes.io/name: xet-csi-driver
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xet-csi-node-role
  labels:
    app.kubernetes.io/name: xet-csi-driver
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xet-csi-node-binding
  labels:
    app.kubernetes.io/name: xet-csi-driver
subjects:
  - kind: ServiceAccount
    name: xet-csi-node-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: xet-csi-node-role
  apiGroup: rbac.authorization.k8s.io
